// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFSnp0XWSHVsHci4T9sZw0HSYK9lHLEQ',
    appId: '1:845720287549:web:262d94a66c0b61c24bed54',
    messagingSenderId: '845720287549',
    projectId: 'namastee-b60cd',
    authDomain: 'namastee-b60cd.firebaseapp.com',
    storageBucket: 'namastee-b60cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRVOzo-SXqcxNTvh-lZJl9pTqvjwQU6w',
    appId: '1:845720287549:android:8ff7ef607e2b6ac74bed54',
    messagingSenderId: '845720287549',
    projectId: 'namastee-b60cd',
    storageBucket: 'namastee-b60cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyUPs2pfwzjb3DyY-byBA3tvX3meW_xE',
    appId: '1:845720287549:ios:f5a6d0c893b0cf474bed54',
    messagingSenderId: '845720287549',
    projectId: 'namastee-b60cd',
    storageBucket: 'namastee-b60cd.appspot.com',
    androidClientId: '845720287549-d5jbcm8joa521mnmksevvmts8uijj2ev.apps.googleusercontent.com',
    iosClientId: '845720287549-v3nggn8nb40vm2p5l01bkto3t5ua5sqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyUPs2pfwzjb3DyY-byBA3tvX3meW_xE',
    appId: '1:845720287549:ios:91b6e68d7108b13a4bed54',
    messagingSenderId: '845720287549',
    projectId: 'namastee-b60cd',
    storageBucket: 'namastee-b60cd.appspot.com',
    androidClientId: '845720287549-d5jbcm8joa521mnmksevvmts8uijj2ev.apps.googleusercontent.com',
    iosClientId: '845720287549-bl5pfhmqgl68ahcsiu3s30tk9rjpgif6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiichat.RunnerTests',
  );
}
